language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
script:
- python manage.py migrate
- python manage.py test

deploy:
  provider: heroku
  buildpack: heroku/python
  api_key:
    secure: pHTFScAjKRVTyOm8RjZAwqa+byVYyex1sWvUO2B3wcyctRJxNVKd7cjbXN0NULz2VJORYnvxSeBuFbZqNvCHac5xvbCxs3slmrwczXw0UyD39nvz0AytcZb9PcGQI3ZE2/3EneePOaP3uGVAevRxOij1/Np8rn2zqz68aVIy59hrKClCV64IDn8siXjHo7C9+AafmthuYVuPT513dwCbFI95ASj6UlhAXyrxkvyM9iUz2aO/7DZDiGgItAF5OV/H2eZ8QzEX8h68q4gpDXbYK/pn7qn1/bLueEC+ekPnEf+1g584+AjXOLfc6Z/6YlImO8F947YWIgnOg1KJiZazy9P70XjP9eyIyk+aOnwxi+QpeZcPU4RjZHTAsFJ5Dz3GqVUZp20gWpUYfgMY2aArgW+yLjBVcqogbeBZTg7b72KRHUU7axCVe/NOVMbfau9e9H/Y30uMBLtooDChqSaT/TJCc/tavMuejRjq0VIGEmsaREkfqRJb4MwXITjf/kDCvdLUSnw+eTVjn0uYxhcSJB3ge8pCEJzi748giud7HaLE4cWVaao01w5l3cqqf0KJoEEKcHssz3t3kV8QZxixFeZDpHEtKObfColZxY7uHCPXJT4ycOnJpsoEpQE9+NLe3zx49fcQ9Rzqa5UR4044LrLiH4JynhUQ5M57IM2yL88=
  app: westbank
  on:
    repo: EvgenyPopov72/WestBank
  run:
    - "python manage.py migrate"
